spring.application.name=chitfund-backend


spring.datasource.url=jdbc:postgresql://localhost:5432/chitfund_db
spring.datasource.username=rahul
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true