apiVersion: apps/v1
kind: Deployment
metadata:
  name: chitfund-backend
  labels:
    app: chitfund-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: chitfund-backend
  template:
    metadata:
      labels:
        deployment: chitfund-backend
    spec:
      containers:
        - name: chitfund-backend
          image: image-registry.openshift-image-registry.svc:5000/rahulkai-dev/chitfund-backend:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5